fix: [climate] Allow substitutions in `visual.temperature_step.{target_temperature,current_temperature}`
The change addresses the error being raised when using substitutions in
`visual.temperature_step`, `target_temperature` and
`current_temperature` properties (see below for details on the error).

Basically, `visual.temperature_step` is now attempted as schema of
separate values first, and then falls back to single value for both.
Previously, the single value case has been processed first for schema
interpretation and skipped `cv.temperature()` call on those, hence
substitutions remain strings not floats.

	src/main.cpp: In function 'void setup()':
	src/main.cpp:135:85: error: no matching function for call to 'esphome::thermostat::ThermostatClimate::set_visual_temperature_step_override(const char [4], const char [4])'
	   thermostat_thermostatclimate_id->set_visual_temperature_step_override("0.5", "0.1");
											     ^
	In file included from src/esphome/components/climate/automation.h:4,
			 from src/esphome.h:3,
			 from src/main.cpp:3:
	src/esphome/components/climate/climate.h:250:8: note: candidate: 'void esphome::climate::Climate::set_visual_temperature_step_override(float, float)'
	   void set_visual_temperature_step_override(float target, float current);
		^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	src/esphome/components/climate/climate.h:250:8: note:   no known conversion for argument 1 from 'const char [4]' to 'float'
	*** [.pioenvs/componenttestesp32ard/src/main.cpp.o] Error 1